# Generated by Django 4.0.3 on 2022-04-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('Area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Center_atitude', models.FloatField(default=0)),
                ('Center_longitude', models.FloatField(default=0)),
                ('Radius', models.FloatField()),
                ('Creation_date', models.DateField()),
                ('Is_Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('Network_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Network_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('Store_id', models.AutoField(primary_key=True, serialize=False)),
                ('Store_atitude', models.FloatField(default=0)),
                ('Store_longitude', models.FloatField(default=0)),
                ('Network_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards_manager.networks')),
            ],
        ),
        migrations.CreateModel(
            name='Area_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards_manager.areas')),
                ('Store_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards_manager.stores')),
            ],
        ),
    ]
